### ISSUE TITLE
The asset "tailwind.css" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by Aikufurr** [Freika/dawarich#11]
App runs without exiting but fails to display webpage due to missing asset.

Screenshot of webpage.
![23642876345981](https://github.com/Freika/dawarich/assets/51518624/8e594fa3-bc15-4611-9aec-1909ae6c40a3)

Logs from dawarich_app:
```
1 gem installed
Creating database dawarich_development...
Database 'dawarich_development' already exists
Database 'dawarich_test' already exists
PostgreSQL is ready. Running database migrations...
01:07:19 web.1  | started with pid 44
01:07:19 css.1  | started with pid 45
01:07:21 web.1  | => Booting Puma
01:07:21 web.1  | => Rails 7.1.3.2 application starting in development 
01:07:21 web.1  | => Run `bin/rails server --help` for more startup options
01:07:22 web.1  | Puma starting in single mode...
01:07:22 web.1  | * Puma version: 6.4.2 (ruby 3.2.3-p157) ("The Eagle of Durango")
01:07:22 web.1  | *  Min threads: 5
01:07:22 web.1  | *  Max threads: 5
01:07:22 web.1  | *  Environment: development
01:07:22 web.1  | *          PID: 44
01:07:22 web.1  | * Listening on http://0.0.0.0:3000
01:07:22 web.1  | Use Ctrl-C to stop
01:07:24 css.1  | 
01:07:24 css.1  | Rebuilding...
01:07:24 css.1  | Error: Cannot find module 'daisyui'
01:07:24 css.1  | Require stack:
01:07:24 css.1  | - /var/app/config/tailwind.config.js
01:07:24 css.1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
01:07:24 css.1  |     at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
01:07:24 css.1  |     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
01:07:24 css.1  |     at Function.resolve (/snapshot/tailwindcss/standalone-cli/patch-require.js:34:38)
01:07:24 css.1  |     at _resolve (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:250334)
01:07:24 css.1  |     at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:252917)
01:07:24 css.1  |     at /var/app/config/tailwind.config.js:17:5
01:07:24 css.1  |     at evalModule (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:255614)
01:07:24 css.1  |     at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:253542)
01:07:24 css.1  |     at /snapshot/tailwindcss/lib/lib/load-config.js:48:30 {
01:07:24 css.1  |   code: 'MODULE_NOT_FOUND',
01:07:24 css.1  |   requireStack: [ '/var/app/config/tailwind.config.js' ]
01:07:24 css.1  | }
01:08:13 web.1  | Started GET "/" for xxx.xxx.xxx.xxx at 2024-04-08 01:08:13 +0000
01:08:13 web.1  |   ActiveRecord::SchemaMigration Load (3.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
01:08:13 web.1  | Processing by HomeController#index as HTML
01:08:14 web.1  |   Rendering layout layouts/application.html.erb
01:08:14 web.1  |   Rendering home/index.html.erb within layouts/application
01:08:14 web.1  |   Rendered home/index.html.erb within layouts/application (Duration: 1.2ms | Allocations: 511)
01:08:14 web.1  |   Rendered layout layouts/application.html.erb (Duration: 26.1ms | Allocations: 3679)
01:08:14 web.1  | Completed 500 Internal Server Error in 51ms (ActiveRecord: 0.0ms | Allocations: 11396)
01:08:14 web.1  | 
01:08:14 web.1  | 
01:08:14 web.1  |   
01:08:14 web.1  | ActionView::Template::Error (The asset "tailwind.css" is not present in the asset pipeline.
01:08:14 web.1  | ):
01:08:14 web.1  |      9:     <link href="https://cdn.jsdelivr.net/npm/daisyui@4.9.0/dist/full.css" rel="stylesheet" type="text/css">
01:08:14 web.1  |     10:     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
01:08:14 web.1  |     11: 
01:08:14 web.1  |     12:     <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
01:08:14 web.1  |     13:     <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
01:08:14 web.1  |     14:     <%= javascript_importmap_tags %>
01:08:14 web.1  |     15:   </head>
01:08:14 web.1  |   
01:08:14 web.1  | app/views/layouts/application.html.erb:12
```

**Comment by puhtahtoe** [comment]
I'm seeing this error too.

Here's the contents of my docker-compose.yml

````
version: '3'

networks:
  dawarich:

services:
  dawarich_redis:
    image: redis:7.0-alpine
    command: redis-server
    networks:
      - dawarich
    volumes:
      - ./shared_data:/var/shared/redis
  dawarich_db:
    image: postgres:14.2-alpine
    container_name: dawarich_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./shared_data:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - ./gem_cache:/usr/local/bundle/gems
    networks:
      - dawarich
    ports:
      - 2000:3000
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MINIMUM_POINTS_IN_CITY: 5
      APPLICATION_HOST: localhost
    depends_on:
      - dawarich_db
      - dawarich_redis
  dawarich_sidekiq:
    image: freikin/dawarich:0.1.6.1
    container_name: dawarich_sidekiq
    volumes:
      - ./gem_cache:/usr/local/bundle/gems
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
    depends_on:
      - dawarich_db
      - dawarich_redis
      - dawarich_app
````

**Comment by Freika** [comment]
@puhtahtoe @Aikufurr can you try with release 0.1.7.3?

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.1.8

**Comment by salzig** [comment]
Errors seems to be still present with Docker Image freikin/dawarich:0.13.5

**Comment by alexbarcelo** [comment]
@salzig I had some mishaps when trying production mode, and started issue #242 

After the `bundle exec rake assets:precompile` the tailwind error disappeared on my end but other errors appeared, as stated in that issue.
