### ISSUE TITLE
France flag not being displayed

### ISSUE THREAD

**Issue by brewston** [Freika/dawarich#1204]
**OS & Hardware**
 Ubuntu on proxmox

**Version**
0.26.1

**Describe the bug**
The screen that shows countries visited displays their flags, but not for France

**To Reproduce**
You need a visit to France in your history :)
click on 'countries and cities' for the year you visted
expect to see french flag, get 🇒🇞🇞 instead

**Expected behavior**
The french flag 

**Screenshots**
I will add

**Logs**

**Additional context**

![Image](https://github.com/user-attachments/assets/edebb3de-3d8a-41ff-b28b-44fcb09467ec)

**Comment by MeijiRestored** [comment]
I have the same issue

![Image](https://github.com/user-attachments/assets/93ed0720-d42c-461d-a299-517b523a7803)

**Comment by brewston** [comment]
I took a look (I'm bored) in console and I can see  

`[16] pry(main)> def country_to_code(country_name)
[16] pry(main)>     mapping = Country.names_to_iso_a2
[16] pry(main)> 
[16] pry(main)>     return mapping[country_name] if mapping[country_name]
[16] pry(main)> 
[16] pry(main)>     mapping.each do |name, code|
[16] pry(main)>       return code if country_name.downcase == name.downcase
[16] pry(main)>       return code if country_name.downcase.include?(name.downcase) || name.downcase.include?(country_name.downcase)
[16] pry(main)>     end
[16] pry(main)> 
[16] pry(main)>     nil
[16] pry(main)>   end
=> :country_to_code
[17] pry(main)> country_to_code('united kingdom')
D, [2025-05-18T16:37:23.421432 #10141] DEBUG -- :   Country Pluck (1.1ms)  SELECT "countries"."name", "countries"."iso_a2" FROM "countries"
=> "GB"
[18] pry(main)> country_to_code('mexico')
D, [2025-05-18T16:37:29.742650 #10141] DEBUG -- :   Country Pluck (0.7ms)  SELECT "countries"."name", "countries"."iso_a2" FROM "countries"
=> "MX"
[19] pry(main)> country_to_code('france')
D, [2025-05-18T16:37:37.431767 #10141] DEBUG -- :   Country Pluck (0.7ms)  SELECT "countries"."name", "countries"."iso_a2" FROM "countries"
=> "-99"
[20] pry(main)> `

so it appears to me (based on that SELECT statement) that it's looking the country code up in the database and France is missing ?

**Comment by Freika** [comment]
Yup, source json with countries border for some reason had "-99" for both iso2 and iso3 for France, will be fixed in the next release

**Comment by brewston** [comment]
This is fixed for me in 0.26.3 - thanks for such a quick resolution :)

**Comment by gesus14** [comment]
I read that this issue should have been fixed in 0.26.3.

I am running 0.26.6 and facing this issue tough. 

![Image](https://github.com/user-attachments/assets/b79d325d-601c-4e77-b97e-7e79f87cb1f8)

**Comment by Fuguito** [comment]
I am using version 0.27.2 and can't see any flag. Any idea how to solve this?

![Image](https://github.com/user-attachments/assets/fb6c9a38-1a6f-4ea3-93a2-f5cfe3da7fc0)

**Comment by brammp** [comment]
It looks is that lib/assets/countries.geojson is updated,  but the countries table in my DB still shows -99  for France,
My guess is it  looks here for the ISO string for the flags.
If that is the case there a way  to re-generate the table using the updated geojson?

and could this be caused by the fact that i may have skipped a version or 2

**Comment by christian-ho** [comment]
For me this issue is still present as well. (V1.04)
