### ISSUE TITLE
Photos still not visible on map

### ISSUE THREAD

**Issue by drjakub** [Freika/dawarich#1608]
**OS & Hardware**
Provide your software and hardware specs
OpenSuse, docker

**Version**
Provide the version of Dawarich you're experiencing the problem on.
0.30.7

**Describe the bug**

After upgrading to latest version images from Photoprism are still not visible in maps, tried creating trip as a workaround but still no any images are shown, there is no any errors visible in the logs:

method=GET path=/api/v1/photos format=*/* controller=Api::V1::PhotosController action=index status=200 allocations=1848 duration=4.34 view=0.11 db=0.65

**Comment by matze939939** [comment]
Same Problem Here. No Photos shown in Map.

**Comment by philterkaffee** [comment]
Same Problem Here. No Photos shown in Map.

**Comment by RodoMa92** [comment]
Same here, but using Immich as a backend. No evident errors in logs here.

**Comment by kalipso-cyber** [comment]
Same here; using Immich and I don't see a single image anywhere.

**Comment by michaelcresswell** [comment]
The photos layer works correctly for me on desktop web browsers but does not work on iOS web browsers. Just curious, what are other people experiencing this issue using?

**Comment by jlg78fr** [comment]
Hi
I have the same issue with Immich, no pictures are shown, and I get a error message "Failed to fetch Photos"

Windows WSL/ Docker compose
Ver  0.30.12

Log message 
{"method":"GET","path":"/api/v1/photos/5bdf05e7-efa1-4abf-ac26-dda3a162e274/thumbnail.jpg","format":"jpeg","controller":"Api::V1::PhotosController","action":"thumbnail","status":403,"allocations":2125,"duration":16.8,"view":0.3,"db":2.0}

Tried both with desktop Edge & Firefox
Tried changing the Immich API key with full access (not just read)

(the same in Trips, no photos are shown)

Thanks

**Comment by r3df0chs** [comment]
I think this issue and this one are probably the same: (but immich in the other issue)
https://github.com/Freika/dawarich/issues/1071

In the other issues is a workaround is stated, it is working for me.

If you select today/7 days/last month and select the photo layer, _it doesn't work._
If you select today/7 days/last month, press search, and THEN select the photo layer, **it works.**

**Comment by jlg78fr** [comment]
Hi, yes

The workaround works for maps but not for trips.

Also, Immich geolocalisation data is all over the place

Is there a way to delete it from the data base?

Thanks

**Comment by r3df0chs** [comment]
mmh, for me photos are working in trips and with the workaround on normal page. I use immich.

I added also the "asset.view" and "asset.statistics" permission to the immich API key BEFORE i created the trip.

**Comment by sneak-it** [comment]
+1 to this, getting 403 errors in client console (which also passes API key to clients) despite giving the API key full permissions. No relevant error logs that I can see in the server.

```
GET https://dawarich.local.xx.com/api/v1/photos/e45c92fe-150c-4ecb-9682-ee1d6af892a7/thumbnail.jpg?api_key=3762ac1edf740bae0fbxxb0e12ce3c8f&source=immich 403 (Forbidden)
photos:60 Failed to load photo 920f9659-d803-46b0-a4dc-de1c00210685
img.onerror	@	photos:60
```

Docker deployment, Dawarich 0.32.0, Immich 1.142.1.

**Comment by fahwayn** [comment]
The issue is still present on Dawarich 0.35.1 with Immich 2.2.2, both running in containers.
QuTS hero h5.2.7.3297
Docker version 27.1.2-qnap7, build d46fd47

request: GET	https://dawarich.host/api/v1/photos?api_key=fake_api_key&start_date=2025-11-10 00:00:00 +0100&end_date=2025-11-10 23:59:59 +0100

Dawarich container log:
```
==== IMMICH RESPONSE ====

{"message" => "takenAfter must be a date string", "error" => "Bad Request", "statusCode" => 400, "correlationId" => "uuj5wlul"}
method=GET path=/api/v1/photos format=html controller=Api::V1::PhotosController action=index status=200 allocations=5442 duration=58.23 view=0.19 db=1.32
```

**Comment by kiber-io** [comment]
> {"message" => "takenAfter must be a date string", "error" => "Bad Request", "statusCode" => 400, "correlationId" => "uuj5wlul"}

i'm having a similar error on 0.36.0

**Comment by TheMagnetar** [comment]
I cannot see any photos imported from Immich on [0.37.2](https://github.com/Freika/dawarich/releases/latest). I keep getting "Failed to fetch Images" with an API Key with asset.read

**Comment by StasySofts** [comment]
> I cannot see any photos imported from Immich on [0.37.2](https://github.com/Freika/dawarich/releases/latest). I keep getting "Failed to fetch Images" with an API Key with asset.read

Try creating an API Key with both "asset.read" and "asset.show".

**Comment by StasySofts** [comment]
On my PhotoPrism Server (runs as Proxmox LXC), I enabled "Debug Logs" in the advanced settings.
Then I opened a bash on the PhotoPrism Server and executed: "tail -f /opt/photoprism/storage/photoprism.log"
This shows me new log entries in real time.

Now, when loading Dawarich Map with activated photo layer by a URL like this

`https://dawarich.mydomain.de/map/v2?start_at=2026-01-11T00%3A00&end_at=2026-01-11T23%3A59&commit=Search`

there is a XHR Request to

`https://dawarich.mydomain.de/api/v1/photos?start_date=2026-01-11T00:00+01:00&end_date=2026-01-11T23:59+01:00`

The response is an empty result "[]".

At exactly that point, the PhotoPrism Server logs these entries:

```
time="2026-02-14T18:39:12+01:00" level=debug msg="api: aborting request with error code 400 (dies ist nicht möglich)"
time="2026-02-14T18:39:12+01:00" level=debug msg="server: GET /api/v1/photos?q=&public=true&quality=3&after=2026-01-11T00%3A00%2B01%3A00&count=1000&before=2026-01-11T23%3A59%2B01%3A00 (400) [231.647µs]"
```

Manually calling the URL from the Dawarich server in a bash via curl

```
curl -sS -H "Authorization: Bearer <PHOTOPRISM_API_KEY>" http://192.168.0.28:2342/api/v1/photos?q=&public=true&quality=3&after=2026-01-11
T00%3A00%2B01%3A00&count=1000&before=2026-01-11T23%3A59%2B01%3A00
```

also gives error 400.

Then I executed the curl command on the PhotoPrism server using the same URL (I only changed the IP to 127.0.0.1):

```
curl -sS -H "Authorization: Bearer <PHOTOPRISM_API_KEY>" http://127.0.0.1:2342/api/v1/photos?q=&public=true&quality=3&after=2026-01-11
T00%3A00%2B01%3A00&count=1000&before=2026-01-11T23%3A59%2B01%3A00
```

It also gives the error 400.

When I run 

`curl -sS -H "Authorization: Bearer <PHOTOPRISM_API_KEY>" "http://127.0.0.1:2342/api/v1/photos?count=1"`

on both PhotoPrism server (using 127.0.0.1) or Dawarich server (using 192.168.0.28, the PhotoPrism IP) I get a valid result (JSON data).

So I think that the request that Dawarich sends to PhotoPrism is somehow wrong.
Maybe the "q", "public" or "quality" parameters are not allowed or valid.

**Comment by TheMagnetar** [comment]
> > I cannot see any photos imported from Immich on [0.37.2](https://github.com/Freika/dawarich/releases/latest). I keep getting "Failed to fetch Images" with an API Key with asset.read
> 
> Try creating an API Key with both "asset.read" and "asset.show".

No, that did not solve the issue. It still shows "Failed to Fetch Photos" error

**Comment by schnabelewobski** [comment]
Looks like the before parameter is not providing a full timestamp, could that be the error?

**Comment by bubiman** [comment]
I am new to dawarich and I have this problem too.
The darwarich log says:
`Photoprism photo fetch failed: Request failed:  #400
Photoprism API request params: {q: "", public: true, quality: 3, after: "2026-06-12T00:00+02:00", count: 1000, before: "2026-06-13"}`

The before and after timestamps do not look the same. 

dawarich version: 1.8.1
photoprism version: Build 260601-a7d098548

**Comment by mamo2021** [comment]
The same issue occurs here as well. Photoprism build 260601-a7d098548 with the app password enabled. The requests are reaching the server (as indicated by the "last used" timestamp), but no photos are being retrieved.

I suspect that the query is incorrect or faulty:

time="2026-06-12T19:47:00Z" level=warning msg="audit: xxx.xxx.xxx.xxx › session sessb42mhtyu › photos › form invalid › parsing time '2026-06-05T19:47:00.232Z': extra text: 'T19:47:00.232Z'"
time="2026-06-12T19:47:03Z" level=warning msg="audit: xxx.xxx.xxx.xxx › session sessb42mhtyu › photos › form invalid › parsing time '2026-06-05T19:47:00.232Z': extra text: 'T19:47:00.232Z'"
time="2026-06-12T19:47:06Z" level=warning msg="audit: xxx.xxx.xxx.xxx › session sessb42mhtyu › photos › form invalid › parsing time '2026-06-05T19:47:00.232Z': extra text: 'T19:47:00.232Z'"
time="2026-06-12T19:47:09Z" level=warning msg="audit: xxx.xxx.xxx.xxx › session sessb42mhtyu › photos › form invalid › parsing time '2026-06-05T19:47:00.232Z': extra text: 'T19:47:00.232Z'"

(This ist from the photoprism-log)

**Comment by kraftwerk2020** [comment]
I would guess it doesn't like the decimal seconds.

**Comment by drjakub** [comment]
i tested today and whatever i do i still get 0 photos on map, tried to import data from photoprism again but that doesn't helped, now even on trips photos are not showing (it was work before)

`[dawarich_app] Photoprism photo fetch failed: Request failed: 400
2026-06-26T05:09:58.721903482Z [dawarich_app] Photoprism API request params: {q: "", public: true, quality: 3, after: "2026-06-06T00:00+02:00", count: 1000, before: "2026-06-07T00:00:00+02:00"}
2026-06-26T05:09:58.723460245Z [dawarich_app] {"method":"GET","path":"/api/v1/photos","format":"*/*","controller":"Api::V1::PhotosController","action":"index","status":200,"allocations":4081,"duration":27.28,"view":0.94,"db":1.26}
2026-06-26T05:09:58.726501940Z [dawarich_app]   TRANSACTION (6.7ms)  COMMIT
`

**Comment by StasySofts** [comment]
Bug is still present.

I had to make the following changes to get it to work for me:

File: https://github.com/Freika/dawarich/blob/cc1c483662ce7f8d235045d29fbf69078c3448e7/app/services/photoprism/request_photos.rb


Original code:

```
  def request_params(offset = 0)
    params = offset.zero? ? default_params : default_params.merge(offset: offset)
    params[:before] = (end_date.to_date + 1.day).beginning_of_day.iso8601 if end_date.present?
    params
  end
  
  def default_params
    {
      q: '',
      public: true,
      quality: 3,
      after: start_date,
      count: 1000
    }
  end
```

Replace it with:

```
  def request_params(offset = 0)
    params = offset.zero? ? default_params : default_params.merge(offset: offset)
    params[:before] = (end_date.to_date + 1.day).to_s if end_date.present?
    params
  end
  
  def default_params
    {
      q: '',
      public: true,
      quality: 3,
      after: start_date.to_date.to_s,
      count: 1000
    }
  end
```

Before this modification, my PhotoPrism logged this:
```
time="2026-06-26T06:53:21Z" level=debug msg="api: parsing time \"2026-02-22T00:00:00+00:00\": extra text: \"T00:00:00+00:00\""
time="2026-06-26T06:53:21Z" level=debug msg="api: aborting request with error code 400 (dies ist nicht möglich)"
time="2026-06-26T06:53:21Z" level=debug msg="server: GET /api/v1/photos?q=&public=true&quality=3&after=2026-01-09T01%3A00%2B01%3A00&count=1000&before=2026-02-22T00%3A00%3A00%2B00%3A00 (400) [215.967µs]"
```

And after the modification, my PhotoPrism logged this:
```
time="2026-06-26T07:55:44Z" level=debug msg="photos: found 13 results for public:true dist:2.000000 quality:3 before:2026-02-21 after:2026-01-09 count:1000 [5.286156ms]"
time="2026-06-26T07:55:44Z" level=debug msg="server: GET /api/v1/photos?q=&public=true&quality=3&after=2026-01-09&count=1000&before=2026-02-21 (200) [7.588717ms]"
time="2026-06-26T07:55:44Z" level=debug msg="photos: found 0 results for public:true dist:2.000000 quality:3 before:2026-02-21 after:2026-01-09 count:1000 offset:1000 [1.28659ms]"
time="2026-06-26T07:55:44Z" level=debug msg="server: GET /api/v1/photos?q=&public=true&quality=3&after=2026-01-09&count=1000&offset=1000&before=2026-02-21 (200) [1.627237ms]"
```

I'm pretty sure this is not the final solution, because the modification cuts away hours and minutes. But it may help the devs to understand what's going wrong.

EDIT:
Perhaps this is the definitive solution, because the page at https://docs.photoprism.app/user-guide/search/filters/#filter-reference states that the "before" and "after" filters only accept a date without a time - for example, 2022-01-30.

<img width="787" height="170" alt="Image" src="https://github.com/user-attachments/assets/2e7a2b7a-001d-41d6-b4f2-384934a74049" />

**Comment by kraftwerk2020** [comment]
Potentially using `.getutc.iso8601` would make Photoprism happy, it's hard to tell from it's documentation what it's expectations are, but that matches it's examples.

**Comment by schnabelewobski** [comment]
I fixed the “before” parameter, but forgot the “after” parameter also exists. Will try to fix that this weekend. Am 26.06.2026 um 21:00 schrieb kraftwerk2020 ***@***.***>:﻿kraftwerk2020 left a comment (Freika/dawarich#1608)
Potentially using .getutc.iso8601 would make Photoprism happy, it's hard to tell from it's documentation what it's expectations are, but that matches it's examples.

**Comment by drjakub** [comment]
unfortunately still doesn't work :(

2026-06-27T07:40:36.965358010Z [dawarich_app] Photoprism photo fetch failed: Request failed: 400
2026-06-27T07:40:36.965498362Z [dawarich_app] Photoprism API request params: {q: "", public: true, quality: 3, after: "2026-06-21T00:00+02:00", count: 1000, before: "2026-06-23T00:00:00+02:00"}
2026-06-27T07:40:36.966239974Z [dawarich_app] {"method":"GET","path":"/api/v1/photos","format":"*/*","controller":"Api::V1::PhotosController","action":"index","status":200,"allocations":4057,"duration":35.49,"view":0.08,"db":0.67}

**Comment by StasySofts** [comment]
Fixed in 1.10.0

Thank you so much!

**Comment by mamo2021** [comment]
V 1.10.0: It's working now. Thanks!

By the way: really pretty new design!

**Comment by drjakub** [comment]
It's finally working, thank you so much for fixing this and with new design it's awesome, great work!
