### ISSUE TITLE
Moving point + delete another point

### ISSUE THREAD

**Issue by ajpanton** [Freika/dawarich#1797]
Dawarich version 0.32.0
Browser: tested Firefox and Chrome

Description & steps:
- Go to the map and show both points and routes.
- Move a point. This will both move the point, and update the route lines.
- Delete some other, unrelated point. Your previously moved point will stay, but its route lines will revert back to how they were before the move.

This is a cosmetic issue and does not affect any functionality.

<img width="608" height="673" alt="Image" src="https://github.com/user-attachments/assets/0f71d07a-b98c-4e23-9f0c-057fb1f925fa" />

**Comment by Freika** [comment]
Should be fixed in 1.7.2

**Comment by binnichtaktiv** [comment]
@Freika this isn't completely fixed. I deleted a few inaccurate points I tracked today and the route was displaying weird again until I reloaded the page. After I reloaded it showed correctly again. It's not a big problem because most people probably use map v2 but I still wanted to report this

**Comment by Freika** [comment]
I'd leave it as it is since map v1 will be sunsetted this summer anyway

**Comment by binnichtaktiv** [comment]
Yea no problem I understand that. Just wanted to report this anyway. I’ll switch to v2 now I think. All features I need are there now. Only thing I miss is the extremely detailed map. V2 is also detailed but v1 has even more. Is it possible to add this in the feature?
