### ISSUE TITLE
Line drawing issue when waypoints cross map border

### ISSUE THREAD

**Issue by shanescarlett** [Freika/dawarich#1851]
I often import flight data, but there is an issue when the flight has crossed map borders (roughly somewhere over the Pacific Ocean), the drawn line flips over to the other side.

<img width="1263" height="345" alt="Image" src="https://github.com/user-attachments/assets/3077a8f8-0aa7-48da-9af9-b953855ec522" />

Probably not as straightforward of a fix as it may seem but I think overall the map screen needs to support "infinite scrolling," e.g. allow the map to be panned from Asia over to North America. Right now, it hits this map border and snaps back, which is not so great in terms of UX.

**Comment by binnichtaktiv** [comment]
Just wondering what do you use to import your flight data? I use FlightAware.com but it doesn't save the current speed unfortunately

**Comment by shanescarlett** [comment]
I use flightaware converted to gpx as well, and don't get the speed data either.

**Comment by Freika** [comment]
Should have been fixed a while ago

**Comment by tenjin43** [comment]
I’m still seeing this issue on the current version.

When a trip crosses the International Date Line / antimeridian, the route line in the trip map preview is rendered as an impossible path across the world map instead of crossing the Pacific correctly.

### Environment
- Dawarich version: 1.7.8
- Deployment: Docker Compose
- Browser: Microsoft Edge / Chrome
- View: Trips page

### Example
A trip involving Japan and Hawaii crosses the antimeridian. The actual route should cross the Pacific, but the map preview draws a long horizontal line across the world map.

### Expected behavior
Routes that cross ±180° longitude should be split or wrapped correctly so that the shortest path across the antimeridian is shown.

### Actual behavior
The route is drawn across the whole map, resulting in an impossible route visualization.

This looks similar to #1162 and #1851, but it still appears to be reproducible in Trips previews/cards.

**Comment by Freika** [comment]
@tenjin43 
Screenshot? If it's only on a trip map, please open a separate issue

**Comment by tenjin43** [comment]
Thanks for the reply.
Yes, this issue happens only on the trip map / trip preview. The main map view is rendered correctly.
I opened a separate issue here: #2731
