### ISSUE TITLE
ALLOW_EMAIL_PASSWORD_REGISTRATION and OIDC_AUTO_REGISTER have no effect

### ISSUE THREAD

**Issue by kiber-io** [Freika/dawarich#1972]
**OS & Hardware**
Docker Compose

**Version**
0.36.0

**Describe the bug**
I’m seeing two configuration variables in Dawarich not behaving as expected:

`ALLOW_EMAIL_PASSWORD_REGISTRATION`
Even when set to false, password-based login is still available. The UI and backend continue to allow password login instead of enforcing oauth only.

`OIDC_AUTO_REGISTER`
When set to false, new users should not be auto-created on first OIDC login. However, the system still creates a new user if they don’t exist.

Both variables appear to be ignored at runtime.

**To Reproduce**
1. Set ALLOW_EMAIL_PASSWORD_REGISTRATION=false
2. Set OIDC_AUTO_REGISTER=false
3. Set SELF_HOSTED=true (This is set because the [code](https://github.com/Freika/dawarich/blob/52eb80503d2717e8bc203d440b48d0965e92ebe7/app/helpers/application_helper.rb#L140) appears to ignore ALLOW_EMAIL_PASSWORD_REGISTRATION when SELF_HOSTED=false)
4. Restart services
5. Attempt:
  - Email/password login
  - First-time OIDC login with an unknown user

**Expected behavior**
- Password login should be disabled completely.
- Unknown OIDC users should not be auto-registered.

**Comment by darioackermann** [comment]
I believe `ALLOW_EMAIL_PASSWORD_REGISTRATION` does exactly what it says - enabling/disabling e-mail based **registration**

I agree, though, that an option to disable the form completely would be great

**Comment by kiber-io** [comment]
> I believe `ALLOW_EMAIL_PASSWORD_REGISTRATION` does exactly what it says - enabling/disabling e-mail based **registration**

Oh, I didn’t even think about that xD
It’s just that when OIDC is in play, you can usually disable the classic username-password login entirely to tighten security

**Comment by Bl4ckspell7** [comment]
Same issue for me with `OIDC_AUTO_REGISTER: false`. User gets created.

**Comment by Freika** [comment]
Should be fixed in 1.0.1

**Comment by Bl4ckspell7** [comment]
The email/password registration issue still affects Dawarich `v1.12.2`.

### Configuration

```yaml
SELF_HOSTED: "true"
OIDC_AUTO_REGISTER: "true"
ALLOW_EMAIL_PASSWORD_REGISTRATION: "false"
ALLOW_EMAIL_PASSWORD_LOGIN: "false"
```

The running container contained these values and was recreated after the Compose change.

### Live investigation

```text
ENV["ALLOW_EMAIL_PASSWORD_REGISTRATION"]: "false"
ALLOW_EMAIL_PASSWORD_REGISTRATION constant: false
Rails.cache.read("dawarich/registration_enabled"): true
DawarichSettings.registration_enabled?: true
Redis TTL: -1
```

Therefore, the persistent Redis value overrides the explicitly configured environment variable indefinitely. Recreating the application container does not help because Redis retains the key.

The manual workaround is:

```bash
docker exec dawarich-app bin/rails runner \
  "DawarichSettings.set_registration_enabled(false)"
```

Afterwards, `DawarichSettings.registration_enabled?` returns `false`.

An explicitly supplied environment variable should take precedence over the cached UI setting, or this precedence needs to be clearly documented.

@Freika
