### ISSUE TITLE
Restart Loop on Latest Version (0.36.0)

### ISSUE THREAD

**Issue by wilcochris** [Freika/dawarich#1975]
**BEFORE OPENING AN ISSUE, MAKE SURE YOU READ THIS: https://github.com/Freika/dawarich/issues/1382**

**OS & Hardware**
Debian 12

**Version**
0.36.0

**Describe the bug**
When updating from 0.34.2 to 0.35.0 or 0.36.0, Dawarich gets stuck in a startup loop and will not start

**To Reproduce**
1. Edit Docker Compose
2. Set version to 'Latest'
3. Exit file
4. Pull the container to update it

**Expected behavior**
Update to work and not get stuck in a loop

**Screenshots**

**Logs**
Added

**Additional context**
Compose file also added
I have another instance that is on the latest version and using production and this doesn't have an issue.
The instance with the issue has it whether it is dev or prod on the latest version

[d-og-app_logs.txt](https://github.com/user-attachments/files/23780312/d-og-app_logs.txt)

[dawarich-docker-compose.yml](https://github.com/user-attachments/files/23780315/dawarich-docker-compose.yml)

**Comment by lexinger** [comment]
same problem here

**Comment by AndDiSa** [comment]
I suppose it's the same as https://github.com/Freika/dawarich/issues/1937

**Comment by rtuszik** [comment]
Should be fixed with #1971

**Comment by wilcochris** [comment]
It definitely isn't fixed. I have just pulled the latest version of the image and it gets stuck in this loop - it doesn't matter if it is prod or dev. It still gets stuck.

I downgrade back to 0.34.2 and everything works as expected.

This is what it keeps churning out in the logs

```
Installing foreman...

/var/app/vendor/bundle/ruby/3.4.0/bin/foreman

Successfully installed foreman-0.90.0

1 gem installed

Starting Foreman with Procfile.prometheus.dev...

/usr/local/bundle/gems/bundler-2.5.21/lib/bundler/rubygems_integration.rb:265:in 'block in Gem.replace_bin_path': can't find executable foreman for gem foreman. foreman is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)

	from /usr/local/bundle/gems/bundler-2.5.21/lib/bundler/rubygems_integration.rb:293:in 'block in Gem.replace_bin_path'

	from /var/app/vendor/bundle/ruby/3.4.0/bin/foreman:25:in '<main>'
```

Then also about OIDC but I don't plan on using that.

**Comment by Freika** [comment]
Should be fixed in 0.36.1

**Comment by lexinger** [comment]
> Should be fixed in 0.36.1

yes it is!!!
thank you!
