### ISSUE TITLE
No route lines in new MapLibre-Map [0.36.2]

### ISSUE THREAD

**Issue by JeeSeeNL** [Freika/dawarich#2026]
Hi there,

After upgrading to version 0.36.2 of DaWarIch, and selecting v2 MapLibre in Settings, there's a difference between the old Leaflet Map version according to routelines.

In Leaflet Map the routes are projected the right way:

<img width="1696" height="545" alt="Image" src="https://github.com/user-attachments/assets/5486b28b-c6da-455e-82c3-7c69e15bc394" />

But opening Today after setting the map to MapLibre, the view is very different, and mostly without routelines:

<img width="1821" height="615" alt="Image" src="https://github.com/user-attachments/assets/ccc858a3-5c68-450d-9ce8-317372505a8f" />

Is this something to correct in Settings?

**Comment by elyobelyob** [comment]
Same. I did a big car journey, and only see some very small parts of the journey.

**Comment by raisinbear** [comment]
I surmise it may have to do with the setting to split tracks if points are further than [distance] apart, where [distance] can only be set to a maximum of 5km in metric units?
At least, it does work for tightly spaced tracks I captured in higher resolution, but none of those I recorded in significant location mode with the app.

**Comment by WorldTeacher** [comment]
have the same issue, but in my case it happens in areas of bad gps coverage and the recorded spots are ~30ish seconds apart, but not connected

**Comment by Freika** [comment]
Should be fixed in 0.36.3

**Comment by raisinbear** [comment]
> Should be fixed in 0.36.3

Sorry, doesn‘t appear to change anything on my end. Significant location routes are still not visible in v2, but working flawlessly in v1.

**Comment by binnichtaktiv** [comment]
> > Should be fixed in 0.36.3
> 
> Sorry, doesn‘t appear to change anything on my end. Significant location routes are still not visible in v2, but working flawlessly in v1.

Same here

**Comment by cookie-drummer** [comment]
It's partially fixed for me on 0.36.3. Majority of routes are already correctly displayed using v2, but still - some routes displayed on v1 are missing on v2.

**Comment by sVathis** [comment]
Problem still exists in 0.36.3

<img width="913" height="713" alt="Image" src="https://github.com/user-attachments/assets/b58bfa69-97e5-4092-98cd-1efb4451a553" />
