### ISSUE TITLE
Negative "Geopoints tracked"

### ISSUE THREAD

**Issue by Tom7320** [Freika/dawarich#2054]
**BEFORE OPENING AN ISSUE, MAKE SURE YOU READ THIS: https://github.com/Freika/dawarich/issues/1382**

**OS & Hardware**
Ubuntu Server 24.04.3 LTS
Docker version 29.1.3, build f52814d
Docker Compose version v5.0.0

**Version**
Dawarich 0.36.3

**Describe the bug**
Today I found a negative number of "Geopoints tracked" in stats menu.

**To Reproduce**
Just open the stats page.

**Expected behavior**
No negative number. Since reverse geocoding is not (yet) enabled, I expect a value of 0.

**Screenshots**

<img width="1522" height="280" alt="Image" src="https://github.com/user-attachments/assets/ae60fecd-e40b-4718-a02e-7e42ba78e5cd" />

**Logs**
Nothing special in the logs.

**Additional context**
none

**Comment by binnichtaktiv** [comment]
Run this in terminal to fix it. 

`docker exec -it dawarich_db psql -U postgres -d dawarich_development -c "UPDATE users SET points_count = (SELECT COUNT(*) FROM points WHERE user_id = users.id);"`


Not sure if I understood the problem but the counter cache only updates with Point.create(). All tracking apps and imports use batch operations that skip the counter so it’s always wrong. 

— not sure if that’s actually true it’s just what I (think) I found out

**Comment by Tom7320** [comment]
I don't know why, and I don't understand it, but I can confirm that your solution works. Is it ok to leave this bug report open since it's kind of a workaround, not a real solution. BTW, I'm using the official Dawarich tracking app on iOS...

<img width="1531" height="211" alt="Image" src="https://github.com/user-attachments/assets/117c8bcb-69a1-44b5-9ab8-659cb4669744" />

Thx a lot for the fix  👍

**Comment by Freika** [comment]
Should be fixed in 0.36.4

**Comment by Tom7320** [comment]
Ah! Great! Thank you very much! 👍

**Comment by smauermann** [comment]
I don't think it's solved. I still see negative geopoints in 0.37.2.

<img width="1515" height="275" alt="Image" src="https://github.com/user-attachments/assets/0a08ebce-2a68-48e0-875f-2e78511949f3" />
