### ISSUE TITLE
Error running db migrations from 0.36.3 to 0.37.0 (undefined method 'safety_assured' for an instance of ChangeDigestsDistanceToBigint)

### ISSUE THREAD

**Issue by cvanfleteren** [Freika/dawarich#2090]
The DB migrations are not running for me. This was from a 0.36.3 to 0.37.0 update. 

dawarich-app[21734]:    (0.1ms)  SELECT pg_try_advisory_lock(1300285682869233375)
dawarich-app[21734]:   ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
dawarich-app[21734]:   ActiveRecord::InternalMetadata Load (0.3ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC >
dawarich-app[21734]: Migrating to ChangeDigestsDistanceToBigint (20251227223614)
dawarich-app[21734]: == 20251227223614 ChangeDigestsDistanceToBigint: migrating ====================
dawarich-app[21734]: -- safety_assured(nil)
dawarich-app[21734]:    (0.1ms)  SELECT pg_advisory_unlock(1300285682869233375)
dawarich-app[21734]: bin/rails aborted!
dawarich-app[21734]: StandardError: An error has occurred, all later migrations canceled: (StandardError)
dawarich-app[21734]: 
dawarich-app[21734]: undefined method 'safety_assured' for an instance of ChangeDigestsDistanceToBigint
dawarich-app[21734]: /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.3/lib/active_record/migration.rb:1054:in 'block in ActiveRecord::Migration#method_missing'
dawarich-app[21734]: /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.3/lib/active_record/migration.rb:1021:in 'block in ActiveRecord::Migration#say_with_time'
dawarich-app[21734]: /var/app/vendor/bundle/ruby/3.4.0/gems/activesupport-8.0.3/lib/active_support/benchmark.rb:17:in 'ActiveSupport::Benchmark.realtime'
dawarich-app[21734]: /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.3/lib/active_record/migration.rb:1021:in 'ActiveRecord::Migration#say_with_time'
dawarich-app[21734]: /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.3/lib/active_record/migration.rb:1044:in 'ActiveRecord::Migration#method_missing'
dawarich-app[21734]: /var/app/db/migrate/20251227223614_change_digests_distance_to_bigint.rb:7:in 'ChangeDigestsDistanceToBigint#up'
dawarich-app[21734]: /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.3/lib/active_record/migration.rb:993:in 'Kernel#public_send'
dawarich-app[21734]: /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.3/lib/active_record/migration.rb:993:in 'ActiveRecord::Migration#exec_migration'
dawarich-app[21734]: /var/app/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.3/lib/active_record/migration.rb:974:in 'block (2 levels) in ActiveRecord::Migration#migrate'
dawarich-app[21734]: /var/app/vendor/bundle/ruby/3.4.0/gems/activesupport-8.0.3/lib/active_support/benchmark.rb:17:in 'ActiveSupport::Benchmark.realtime'

**Comment by sibberio** [comment]
In my case from 0.36.4 to 0.37.0 I have this error

⏳ Waiting for database dawarich_development to be ready...
✅ PostgreSQL database dawarich_development is ready!
Running migrations for all databases...
Running primary database migrations...
[dotenv] Set OBJC_DISABLE_INITIALIZE_FORK_SAFETY
[dotenv] Loaded .env.development
OIDC: Not configured (missing OIDC_CLIENT_ID or OIDC_CLIENT_SECRET)
   (0.7ms)  SELECT pg_try_advisory_lock(1212213197400985920)
  ActiveRecord::SchemaMigration Load (5.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ActiveRecord::InternalMetadata Load (4.2ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
Migrating to ChangeDigestsDistanceToBigint (20251227223614)
== 20251227223614 ChangeDigestsDistanceToBigint: migrating ====================
-- safety_assured(nil)
   (0.8ms)  SELECT pg_advisory_unlock(1212213197400985920)
bin/rails aborted!

**Comment by SoPat712** [comment]
https://github.com/Freika/dawarich/issues/2091

I closed my issue, but I had a similar problem

Here's some logs:

https://pastebin.com/FJC6BRma
https://pastebin.com/zy5KbmjQ

**Comment by philmichel** [comment]
Having the same issue here.

**Comment by frostworx** [comment]
likely fixed in https://github.com/Freika/dawarich/releases/tag/0.37.1:

```
Fixed

    The db migration preventing the app from starting.
```

**Comment by Freika** [comment]
Yup, should be fixed in 0.37.1

**Comment by dhj65** [comment]
I have just pulled the latest image and still getting the "undefined method 'safety_assured' for an instance of ChangeDigestsDistanceToBigint" error...

Edit: I have issued the pull command again and now a nwer images is found,,, dawarich_app starting fine now.

**Comment by frostworx** [comment]
I can confirm 0.37.1 works just fine.
Thank you very much for your great work, @Freika and have a good start into the new year!
