### ISSUE TITLE
Docker container fails to start up with LoadError /usr/local/bundle/gems/bundler-2.3.3/exe/bundle

### ISSUE THREAD

**Issue by stepsysadmin** [Freika/dawarich#3]
Debian 12, Docker version 25.0.3, build 4debf41, docker-compose version 1.29.2, build unknown

```Attaching to dawarich_db, dawarich_dawarich_redis_1, dawarich_sidekiq, dawarich_app
dawarich_app        | Environment: development
dawarich_app        | dawarich_db (172.23.0.3:5432) open
dawarich_app        | Creating database dawarich_development...
dawarich_redis_1    | 1:C 24 Mar 2024 21:05:15.798 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
dawarich_redis_1    | 1:C 24 Mar 2024 21:05:15.798 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
dawarich_redis_1    | 1:C 24 Mar 2024 21:05:15.798 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
dawarich_redis_1    | 1:M 24 Mar 2024 21:05:15.798 * monotonic clock: POSIX clock_gettime
dawarich_redis_1    | 1:M 24 Mar 2024 21:05:15.799 * Running mode=standalone, port=6379.
dawarich_redis_1    | 1:M 24 Mar 2024 21:05:15.799 # Server initialized
dawarich_redis_1    | 1:M 24 Mar 2024 21:05:15.799 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
dawarich_redis_1    | 1:M 24 Mar 2024 21:05:15.799 * Loading RDB produced by version 7.0.15
dawarich_redis_1    | 1:M 24 Mar 2024 21:05:15.799 * RDB age 286 seconds
dawarich_redis_1    | 1:M 24 Mar 2024 21:05:15.799 * RDB memory usage when created 0.82 Mb
dawarich_redis_1    | 1:M 24 Mar 2024 21:05:15.799 * Done loading RDB, keys loaded: 0, keys expired: 0.
dawarich_redis_1    | 1:M 24 Mar 2024 21:05:15.799 * DB loaded from disk: 0.000 seconds
dawarich_redis_1    | 1:M 24 Mar 2024 21:05:15.799 * Ready to accept connections
dawarich_db         |
dawarich_db         | PostgreSQL Database directory appears to contain a database; Skipping initialization
dawarich_db         |
dawarich_db         | 2024-03-24 21:05:15.831 UTC [1] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
dawarich_db         | 2024-03-24 21:05:15.831 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dawarich_db         | 2024-03-24 21:05:15.831 UTC [1] LOG:  listening on IPv6 address "::", port 5432
dawarich_db         | 2024-03-24 21:05:15.882 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dawarich_db         | 2024-03-24 21:05:15.887 UTC [21] LOG:  database system was shut down at 2024-03-24 21:00:29 UTC
dawarich_db         | 2024-03-24 21:05:15.894 UTC [1] LOG:  database system is ready to accept connections
dawarich_sidekiq    | Environment: development
dawarich_sidekiq    | dawarich_db (172.23.0.3:5432) open
dawarich_sidekiq    | Creating database dawarich_development...
dawarich_sidekiq    | /usr/local/bundle/bin/bundle:25:in `load': cannot load such file -- /usr/local/bundle/gems/bundler-2.3.3/exe/bundle (LoadError)
dawarich_sidekiq    |   from /usr/local/bundle/bin/bundle:25:in `<main>'
dawarich_app        | /usr/local/bundle/bin/bundle:25:in `load': cannot load such file -- /usr/local/bundle/gems/bundler-2.3.3/exe/bundle (LoadError)
dawarich_app        |   from /usr/local/bundle/bin/bundle:25:in `<main>'
dawarich_sidekiq exited with code 1
dawarich_app exited with code 1```

**Comment by bobvmierlo** [comment]
Having the same issue on a fresh install, following the progress

**Comment by Freika** [comment]
@bobvmierlo @stepsysadmin can you please try again, changing version to 0.1.4.1 in docker-compose.yml? It should be fixed now

**Comment by Aikufurr** [comment]
Running into the same issue, forked the project and added a [workflow](https://github.com/Aikufurr/dawarich/blob/master/.github/workflows/docker-image.yml) to compile a docker image for AMD and ARM. Works fine when compiled for arm but still running into this particular issue when building from `main`.

Logs from: dawarich_sidekiq
```
Fetching bundler-2.5.7.gem
Successfully installed bundler-2.5.7
1 gem installed

A new release of RubyGems is available: 3.4.19 → 3.5.7!
Run `gem update --system 3.5.7` to update your installation.

Creating database dawarich_development...
/usr/local/bundle/gems/bundler-2.5.7/lib/bundler.rb:3:in `require_relative': cannot load such file -- /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/vendored_fileutils (LoadError)
	from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler.rb:3:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/local/bundle/gems/bundler-2.5.7/exe/bundle:16:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'
```

OS: Ubuntu 22.04.4 LTS aarch64 
Kernel: 5.15.0-101-generic 
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

**Comment by stepsysadmin** [comment]
I have updated the docker-compose.yml with the new version, however now it seems that the error is simply ignored:

```
root@debian:~/docker-stuff/dawarich# docker compose up
WARN[0000] /root/docker-stuff/dawarich/docker-compose.yml: `version` is obsolete 
[+] Running 3/0
 ✔ Container dawarich_sidekiq           Created                                                                    0.1s 
 ✔ Container 24b2dbce77a3_dawarich_app  Removed                                                                    0.0s 
 ✔ Container dawarich_app               Recreated                                                                  0.1s 
Attaching to dawarich_redis-1, dawarich_app, dawarich_db, dawarich_sidekiq
dawarich_redis-1  | 1:C 05 Apr 2024 04:17:03.823 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
dawarich_redis-1  | 1:C 05 Apr 2024 04:17:03.825 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
dawarich_redis-1  | 1:C 05 Apr 2024 04:17:03.825 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
dawarich_redis-1  | 1:M 05 Apr 2024 04:17:03.828 * monotonic clock: POSIX clock_gettime
dawarich_redis-1  | 1:M 05 Apr 2024 04:17:03.830 * Running mode=standalone, port=6379.
dawarich_redis-1  | 1:M 05 Apr 2024 04:17:03.830 # Server initialized
dawarich_redis-1  | 1:M 05 Apr 2024 04:17:03.832 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
dawarich_redis-1  | 1:M 05 Apr 2024 04:17:03.834 * Loading RDB produced by version 7.0.15
dawarich_redis-1  | 1:M 05 Apr 2024 04:17:03.835 * RDB age 20 seconds
dawarich_redis-1  | 1:M 05 Apr 2024 04:17:03.836 * RDB memory usage when created 0.82 Mb
dawarich_redis-1  | 1:M 05 Apr 2024 04:17:03.836 * Done loading RDB, keys loaded: 0, keys expired: 0.
dawarich_redis-1  | 1:M 05 Apr 2024 04:17:03.837 * DB loaded from disk: 0.002 seconds
dawarich_redis-1  | 1:M 05 Apr 2024 04:17:03.837 * Ready to accept connections
dawarich_db       | 
dawarich_db       | PostgreSQL Database directory appears to contain a database; Skipping initialization
dawarich_db       | 
dawarich_db       | 2024-04-05 04:17:03.865 UTC [1] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
dawarich_db       | 2024-04-05 04:17:03.865 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dawarich_db       | 2024-04-05 04:17:03.866 UTC [1] LOG:  listening on IPv6 address "::", port 5432
dawarich_db       | 2024-04-05 04:17:03.871 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dawarich_db       | 2024-04-05 04:17:03.877 UTC [21] LOG:  database system was shut down at 2024-04-05 04:16:43 UTC
dawarich_db       | 2024-04-05 04:17:03.881 UTC [1] LOG:  database system is ready to accept connections
dawarich_sidekiq  | Environment: development
dawarich_sidekiq  | dawarich_db (172.21.0.2:5432) open
dawarich_app      | Environment: development
dawarich_app      | dawarich_db (172.21.0.2:5432) open
dawarich_app      | Creating database dawarich_development...
dawarich_app      | /usr/local/bundle/bin/bundle:25:in `load': cannot load such file -- /usr/local/bundle/gems/bundler-2.3.3/exe/bundle (LoadError)
dawarich_app      | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
dawarich_app exited with code 1
dawarich_sidekiq  | Updating rubygems-update
dawarich_sidekiq  | Fetching rubygems-update-3.5.7.gem
dawarich_sidekiq  | Successfully installed rubygems-update-3.5.7
dawarich_sidekiq  | Installing RubyGems 3.5.7
dawarich_sidekiq  |   Successfully built RubyGem
dawarich_sidekiq  |   Name: bundler
dawarich_sidekiq  |   Version: 2.5.7
dawarich_sidekiq  |   File: bundler-2.5.7.gem
dawarich_sidekiq  | Bundler 2.5.7 installed
dawarich_sidekiq  | RubyGems 3.5.7 installed
dawarich_sidekiq  | Regenerating binstubs
dawarich_sidekiq  | Regenerating plugins
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.5.7 / 2024-03-22
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Warn on empty or open required_ruby_version specification attribute.
dawarich_sidekiq  |   Pull request [#5010](https://github.com/rubygems/rubygems/pull/5010) by
dawarich_sidekiq  |   simi
dawarich_sidekiq  | * Control whether YAML aliases are enabled in Gem::SafeYAML.safe_load via
dawarich_sidekiq  |   attribute. Pull request
dawarich_sidekiq  |   [#7464](https://github.com/rubygems/rubygems/pull/7464) by segiddins
dawarich_sidekiq  | * Update SPDX license list as of 2024-02-08. Pull request
dawarich_sidekiq  |   [#7468](https://github.com/rubygems/rubygems/pull/7468) by
dawarich_sidekiq  |   github-actions[bot]
dawarich_sidekiq  | * Installs bundler 2.5.7 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Bug fixes:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Allow prerelease activation (even if requirement is not explicit about
dawarich_sidekiq  |   it) when it's the only possibility. Pull request
dawarich_sidekiq  |   [#7428](https://github.com/rubygems/rubygems/pull/7428) by kimesf
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Documentation:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Fix a typo. Pull request
dawarich_sidekiq  |   [#7505](https://github.com/rubygems/rubygems/pull/7505) by hsbt
dawarich_sidekiq  | * Use https instead of http in documentation links. Pull request
dawarich_sidekiq  |   [#7481](https://github.com/rubygems/rubygems/pull/7481) by hsbt
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.5.6 / 2024-02-06
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Deep copy requirements in `Gem::Specification` and `Gem::Requirement`.
dawarich_sidekiq  |   Pull request [#7439](https://github.com/rubygems/rubygems/pull/7439) by
dawarich_sidekiq  |   flavorjones
dawarich_sidekiq  | * Change gem login message to clear up that username can be also used.
dawarich_sidekiq  |   Pull request [#7422](https://github.com/rubygems/rubygems/pull/7422) by
dawarich_sidekiq  |   VitaliySerov
dawarich_sidekiq  | * Add metadata for rubygems.org. Pull request
dawarich_sidekiq  |   [#7435](https://github.com/rubygems/rubygems/pull/7435) by m-nakamura145
dawarich_sidekiq  | * Improve gem login scope selection. Pull request
dawarich_sidekiq  |   [#7342](https://github.com/rubygems/rubygems/pull/7342) by williantenfen
dawarich_sidekiq  | * Vendor uri in RubyGems. Pull request
dawarich_sidekiq  |   [#7386](https://github.com/rubygems/rubygems/pull/7386) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | * Installs bundler 2.5.6 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Bug fixes:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Skip to load commented out words. Pull request
dawarich_sidekiq  |   [#7413](https://github.com/rubygems/rubygems/pull/7413) by hsbt
dawarich_sidekiq  | * Fix rake runtime dependency warning for rake based extension. Pull
dawarich_sidekiq  |   request [#7395](https://github.com/rubygems/rubygems/pull/7395) by ntkme
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.5.5 / 2024-01-18
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Installs bundler 2.5.5 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Bug fixes:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Fix `require` activation conflicts when requiring default gems under
dawarich_sidekiq  |   some situations. Pull request
dawarich_sidekiq  |   [#7379](https://github.com/rubygems/rubygems/pull/7379) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | * Use cache_home instead of data_home in default_spec_cache_dir. Pull
dawarich_sidekiq  |   request [#7331](https://github.com/rubygems/rubygems/pull/7331) by mrkn
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Documentation:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Use squiggly heredocs in `Gem::Specification#description` documentation,
dawarich_sidekiq  |   so it doesn't add leading whitespace. Pull request
dawarich_sidekiq  |   [#7373](https://github.com/rubygems/rubygems/pull/7373) by bravehager
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.5.4 / 2024-01-04
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Always avoid "Updating rubygems-update" message. Pull request
dawarich_sidekiq  |   [#7335](https://github.com/rubygems/rubygems/pull/7335) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | * Installs bundler 2.5.4 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Bug fixes:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Make `gem update --system` respect ruby version constraints. Pull
dawarich_sidekiq  |   request [#7334](https://github.com/rubygems/rubygems/pull/7334) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.5.3 / 2023-12-22
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Installs bundler 2.5.3 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.5.2 / 2023-12-21
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Support dynamic library loading with extension .so or .o. Pull request
dawarich_sidekiq  |   [#7241](https://github.com/rubygems/rubygems/pull/7241) by hogelog
dawarich_sidekiq  | * Installs bundler 2.5.2 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Performance:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Replace `object_id` comparison with identity Hash. Pull request
dawarich_sidekiq  |   [#7303](https://github.com/rubygems/rubygems/pull/7303) by amomchilov
dawarich_sidekiq  | * Use IO.copy_stream when reading, writing. Pull request
dawarich_sidekiq  |   [#6958](https://github.com/rubygems/rubygems/pull/6958) by martinemde
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.5.1 / 2023-12-15
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Installs bundler 2.5.1 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.5.0 / 2023-12-15
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Security:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Replace `Marshal.load` with a fully-checked safe gemspec loader. Pull
dawarich_sidekiq  |   request [#6896](https://github.com/rubygems/rubygems/pull/6896) by
dawarich_sidekiq  |   segiddins
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Breaking changes:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Drop ruby 2.6 and 2.7 support. Pull request
dawarich_sidekiq  |   [#7116](https://github.com/rubygems/rubygems/pull/7116) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | * Release package no longer includes test files. Pull request
dawarich_sidekiq  |   [#6781](https://github.com/rubygems/rubygems/pull/6781) by hsbt
dawarich_sidekiq  | * Hide `Gem::MockGemUi` from users. Pull request
dawarich_sidekiq  |   [#6623](https://github.com/rubygems/rubygems/pull/6623) by hsbt
dawarich_sidekiq  | * Deprecated `Gem.datadir` has been removed. Pull request
dawarich_sidekiq  |   [#6469](https://github.com/rubygems/rubygems/pull/6469) by hsbt
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Deprecations:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Deprecate `Gem::Platform.match?`. Pull request
dawarich_sidekiq  |   [#6783](https://github.com/rubygems/rubygems/pull/6783) by hsbt
dawarich_sidekiq  | * Deprecate `Gem::List`. Pull request
dawarich_sidekiq  |   [#6311](https://github.com/rubygems/rubygems/pull/6311) by segiddins
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Features:
dawarich_sidekiq  | 
dawarich_sidekiq  | * The `generate_index` command can now generate compact index files and
dawarich_sidekiq  |   lives as an external `rubygems-generate_index` gem. Pull request
dawarich_sidekiq  |   [#7085](https://github.com/rubygems/rubygems/pull/7085) by segiddins
dawarich_sidekiq  | * Make `gem install` fallback to user installation directory if default
dawarich_sidekiq  |   gem home is not writable. Pull request
dawarich_sidekiq  |   [#5327](https://github.com/rubygems/rubygems/pull/5327) by duckinator
dawarich_sidekiq  | * Leverage ruby feature to warn when requiring default gems from stdlib
dawarich_sidekiq  |   that will be turned into bundled gems in the future. Pull request
dawarich_sidekiq  |   [#6840](https://github.com/rubygems/rubygems/pull/6840) by hsbt
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Performance:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Use match? when regexp match data is unused. Pull request
dawarich_sidekiq  |   [#7263](https://github.com/rubygems/rubygems/pull/7263) by segiddins
dawarich_sidekiq  | * Fewer allocations in gem installation. Pull request
dawarich_sidekiq  |   [#6975](https://github.com/rubygems/rubygems/pull/6975) by segiddins
dawarich_sidekiq  | * Optimize allocations in `Gem::Version`. Pull request
dawarich_sidekiq  |   [#6970](https://github.com/rubygems/rubygems/pull/6970) by segiddins
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Warn for duplicate meta data links when building gems. Pull request
dawarich_sidekiq  |   [#7213](https://github.com/rubygems/rubygems/pull/7213) by etherbob
dawarich_sidekiq  | * Vendor `net-http`, `net-protocol`, `resolv`, and `timeout` to reduce
dawarich_sidekiq  |   conflicts between Gemfile gems and internal dependencies. Pull request
dawarich_sidekiq  |   [#6793](https://github.com/rubygems/rubygems/pull/6793) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | * Remove non-transparent requirement added to prerelease gems. Pull
dawarich_sidekiq  |   request [#7226](https://github.com/rubygems/rubygems/pull/7226) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | * Stream output from ext builds when --verbose. Pull request
dawarich_sidekiq  |   [#7240](https://github.com/rubygems/rubygems/pull/7240) by osyoyu
dawarich_sidekiq  | * Add missing services to CI detection and make it consistent between
dawarich_sidekiq  |   RubyGems and Bundler. Pull request
dawarich_sidekiq  |   [#7205](https://github.com/rubygems/rubygems/pull/7205) by nevinera
dawarich_sidekiq  | * Update generate licenses template to not freeze regexps. Pull request
dawarich_sidekiq  |   [#7154](https://github.com/rubygems/rubygems/pull/7154) by
dawarich_sidekiq  |   github-actions[bot]
dawarich_sidekiq  | * Don't check `LIBRUBY_RELATIVE` in truffleruby to signal a bash prelude
dawarich_sidekiq  |   in rubygems binstubs. Pull request
dawarich_sidekiq  |   [#7156](https://github.com/rubygems/rubygems/pull/7156) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | * Update SPDX list and warn on deprecated identifiers. Pull request
dawarich_sidekiq  |   [#6926](https://github.com/rubygems/rubygems/pull/6926) by simi
dawarich_sidekiq  | * Simplify extended `require` to potentially fix some deadlocks. Pull
dawarich_sidekiq  |   request [#6827](https://github.com/rubygems/rubygems/pull/6827) by nobu
dawarich_sidekiq  | * Small refactors for `Gem::Resolver`. Pull request
dawarich_sidekiq  |   [#6766](https://github.com/rubygems/rubygems/pull/6766) by hsbt
dawarich_sidekiq  | * Use double-quotes instead of single-quotes consistently in warnings.
dawarich_sidekiq  |   Pull request [#6550](https://github.com/rubygems/rubygems/pull/6550) by
dawarich_sidekiq  |   hsbt
dawarich_sidekiq  | * Add debug message for `nil` version gemspec. Pull request
dawarich_sidekiq  |   [#6436](https://github.com/rubygems/rubygems/pull/6436) by hsbt
dawarich_sidekiq  | * Installs bundler 2.5.0 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Bug fixes:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Fix installing from source with same default bundler version already
dawarich_sidekiq  |   installed. Pull request
dawarich_sidekiq  |   [#7244](https://github.com/rubygems/rubygems/pull/7244) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Documentation:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Improve comment explaining the necessity of `write_default_spec` method.
dawarich_sidekiq  |   Pull request [#6563](https://github.com/rubygems/rubygems/pull/6563) by
dawarich_sidekiq  |   voxik
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.4.22 / 2023-11-09
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Update SPDX license list as of 2023-10-05. Pull request
dawarich_sidekiq  |   [#7040](https://github.com/rubygems/rubygems/pull/7040) by
dawarich_sidekiq  |   github-actions[bot]
dawarich_sidekiq  | * Remove unnecessary rescue. Pull request
dawarich_sidekiq  |   [#7109](https://github.com/rubygems/rubygems/pull/7109) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | * Installs bundler 2.4.22 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Bug fixes:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Handle empty array at built-in YAML serializer. Pull request
dawarich_sidekiq  |   [#7099](https://github.com/rubygems/rubygems/pull/7099) by hsbt
dawarich_sidekiq  | * Ignore non-tar format `.gem` files during search. Pull request
dawarich_sidekiq  |   [#7095](https://github.com/rubygems/rubygems/pull/7095) by dearblue
dawarich_sidekiq  | * Allow explicitly uninstalling multiple versions of same gem. Pull
dawarich_sidekiq  |   request [#7063](https://github.com/rubygems/rubygems/pull/7063) by
dawarich_sidekiq  |   kstevens715
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Performance:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Avoid regexp match on every call to `Gem::Platform.local`. Pull request
dawarich_sidekiq  |   [#7104](https://github.com/rubygems/rubygems/pull/7104) by segiddins
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Documentation:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Get `Gem::Specification#extensions_dir` documented. Pull request
dawarich_sidekiq  |   [#6218](https://github.com/rubygems/rubygems/pull/6218) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.4.21 / 2023-10-17
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Abort `setup.rb` if Ruby is too old. Pull request
dawarich_sidekiq  |   [#7011](https://github.com/rubygems/rubygems/pull/7011) by
dawarich_sidekiq  |   deivid-rodriguez
dawarich_sidekiq  | * Remove usage of Dir.chdir that only execute a subprocess. Pull request
dawarich_sidekiq  |   [#6930](https://github.com/rubygems/rubygems/pull/6930) by segiddins
dawarich_sidekiq  | * Freeze more strings in generated gemspecs. Pull request
dawarich_sidekiq  |   [#6974](https://github.com/rubygems/rubygems/pull/6974) by segiddins
dawarich_sidekiq  | * Use pure-ruby YAML parser for loading configuration at RubyGems. Pull
dawarich_sidekiq  |   request [#6615](https://github.com/rubygems/rubygems/pull/6615) by hsbt
dawarich_sidekiq  | * Installs bundler 2.4.21 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Documentation:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Update suggested variable for bindir. Pull request
dawarich_sidekiq  |   [#7028](https://github.com/rubygems/rubygems/pull/7028) by hsbt
dawarich_sidekiq  | * Fix invalid links in documentation. Pull request
dawarich_sidekiq  |   [#7008](https://github.com/rubygems/rubygems/pull/7008) by simi
dawarich_sidekiq  | 
dawarich_sidekiq  | # 3.4.20 / 2023-09-27
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Enhancements:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Raise `Gem::Package::FormatError` when gem encounters corrupt EOF.
dawarich_sidekiq  |   Pull request [#6882](https://github.com/rubygems/rubygems/pull/6882)
dawarich_sidekiq  |   by martinemde
dawarich_sidekiq  | * Allow skipping empty license `gem build` warning by setting license to
dawarich_sidekiq  |   `nil`. Pull request
dawarich_sidekiq  |   [#6879](https://github.com/rubygems/rubygems/pull/6879) by jhong97
dawarich_sidekiq  | * Update SPDX license list as of 2023-06-18. Pull request
dawarich_sidekiq  |   [#6891](https://github.com/rubygems/rubygems/pull/6891) by
dawarich_sidekiq  |   github-actions[bot]
dawarich_sidekiq  | * Update SPDX license list as of 2023-04-28. Pull request
dawarich_sidekiq  |   [#6642](https://github.com/rubygems/rubygems/pull/6642) by segiddins
dawarich_sidekiq  | * Update SPDX license list as of 2023-01-26. Pull request
dawarich_sidekiq  |   [#6310](https://github.com/rubygems/rubygems/pull/6310) by segiddins
dawarich_sidekiq  | * Installs bundler 2.4.20 as a default gem.
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Bug fixes:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Fixed false positive SymlinkError in symbolic link directory. Pull
dawarich_sidekiq  |   request [#6947](https://github.com/rubygems/rubygems/pull/6947) by
dawarich_sidekiq  |   negi0109
dawarich_sidekiq  | * Ensure that loading multiple gemspecs with legacy YAML class references
dawarich_sidekiq  |   does not warn. Pull request
dawarich_sidekiq  |   [#6889](https://github.com/rubygems/rubygems/pull/6889) by segiddins
dawarich_sidekiq  | * Fix NoMethodError when choosing a too big number from `gem uni` list.
dawarich_sidekiq  |   Pull request [#6901](https://github.com/rubygems/rubygems/pull/6901) by
dawarich_sidekiq  |   amatsuda
dawarich_sidekiq  | 
dawarich_sidekiq  | ## Performance:
dawarich_sidekiq  | 
dawarich_sidekiq  | * Reduce allocations for stub specifications. Pull request
dawarich_sidekiq  |   [#6972](https://github.com/rubygems/rubygems/pull/6972) by segiddins
dawarich_sidekiq  | 
dawarich_sidekiq  | 
dawarich_sidekiq  | ------------------------------------------------------------------------------
dawarich_sidekiq  | 
dawarich_sidekiq  | RubyGems installed the following executables:
dawarich_sidekiq  | 	/usr/local/bin/gem
dawarich_sidekiq  | 	/usr/local/bin/bundle
dawarich_sidekiq  | 	/usr/local/bin/bundler
dawarich_sidekiq  | 
dawarich_sidekiq  | RubyGems system software updated
dawarich_sidekiq  | Fetching bundler-2.5.7.gem
dawarich_sidekiq  | Successfully installed bundler-2.5.7
dawarich_sidekiq  | 1 gem installed
dawarich_sidekiq  | Creating database dawarich_development...
dawarich_sidekiq  | Created database 'dawarich_development'
dawarich_sidekiq  | Created database 'dawarich_test'
dawarich_sidekiq  | PostgreSQL is ready. Running database migrations...
dawarich_sidekiq  | 
dawarich_sidekiq  | 
dawarich_sidekiq  |                m,
dawarich_sidekiq  |                `$b
dawarich_sidekiq  |           .ss,  $$:         .,d$
dawarich_sidekiq  |           `$$P,d$P'    .,md$P"'
dawarich_sidekiq  |            ,$$$$$b/md$$$P^'
dawarich_sidekiq  |          .d$$$$$$/$$$P'
dawarich_sidekiq  |          $$^' `"/$$$'       ____  _     _      _    _
dawarich_sidekiq  |          $:    ',$$:       / ___|(_) __| | ___| | _(_) __ _
dawarich_sidekiq  |          `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
dawarich_sidekiq  |                 $$:         ___) | | (_| |  __/   <| | (_| |
dawarich_sidekiq  |                 $$         |____/|_|\__,_|\___|_|\_\_|\__, |
dawarich_sidekiq  |               .d$$                                       |_|
dawarich_sidekiq  |       
dawarich_sidekiq  | 
dawarich_sidekiq  | 2024-04-05T04:17:24.044Z pid=42 tid=3dm INFO: Booted Rails 7.1.3.2 application in development environment
dawarich_sidekiq  | 2024-04-05T04:17:24.044Z pid=42 tid=3dm INFO: Running in ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux-musl]
dawarich_sidekiq  | 2024-04-05T04:17:24.044Z pid=42 tid=3dm INFO: See LICENSE and the LGPL-3.0 for licensing details.
dawarich_sidekiq  | 2024-04-05T04:17:24.044Z pid=42 tid=3dm INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
dawarich_sidekiq  | 2024-04-05T04:17:24.044Z pid=42 tid=3dm INFO: Sidekiq 7.2.2 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://dawarich_redis:6379/0"}
dawarich_sidekiq  | 2024-04-05T04:17:24.052Z pid=42 tid=3dm INFO: Sidekiq 7.2.2 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>"redis://dawarich_redis:6379/0"}
dawarich_sidekiq  | 2024-04-05T04:17:24.092Z pid=42 tid=3dm INFO: Cron Jobs - added job with name: stat_creating_job
dawarich_sidekiq  | 2024-04-05T04:17:24.092Z pid=42 tid=3dm INFO: Starting processing, hit Ctrl-C to stop
```

The app container still fails, the error is just skipped over:

```
dawarich_app      | Environment: development
dawarich_app      | dawarich_db (172.23.0.2:5432) open
dawarich_app      | Creating database dawarich_development...
dawarich_app      | /usr/local/bundle/bin/bundle:25:in `load': cannot load such file -- /usr/local/bundle/gems/bundler-2.3.3/exe/bundle (LoadError)
dawarich_app      | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
dawarich_app exited with code 1

```

**Comment by Freika** [comment]
@stepsysadmin so your problem is solved? Don't forget to grab fresh docker-compose.yml before trying to test :)

**Comment by Freika** [comment]
@Aikufurr is your problem solved?

I'm looking into how I can build a docker image for ARM too, thanks! It would be great if you could open a PR :)

**Comment by Aikufurr** [comment]
@Freika PR #9 has been created and the issue for dawarich_sidekiq has been resolved I think, but now something with dawarich_app has arisen, logs below. This code was pulled from main and ran via the github action at the same time as the PR was created.
```
Environment: development
Waiting for PostgreSQL to be ready...
Waiting for PostgreSQL to be ready...
Waiting for PostgreSQL to be ready...
dawarich_db (172.29.0.3:5432) open
Updating rubygems-update
Fetching rubygems-update-3.5.7.gem
Successfully installed rubygems-update-3.5.7
Installing RubyGems 3.5.7
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_file_s_stat - rubygems/commands/mirror_command.rb
	/usr/local/lib/ruby/3.2.0/fileutils.rb:1642:in `stat'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:1642:in `block in install'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:2481:in `block in fu_each_src_dest'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:2497:in `fu_each_src_dest0'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:2479:in `fu_each_src_dest'
	/usr/local/lib/ruby/3.2.0/fileutils.rb:1641:in `install'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:642:in `install_file'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:631:in `block in install_file_list'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:630:in `each'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:630:in `install_file_list'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:317:in `block (2 levels) in install_lib'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:316:in `chdir'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:316:in `block in install_lib'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:311:in `each'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:311:in `install_lib'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/commands/setup_command.rb:164:in `execute'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/command.rb:326:in `invoke_with_build_args'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/command_manager.rb:254:in `invoke_command'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/command_manager.rb:151:in `run'
	/usr/local/bundle/gems/rubygems-update-3.5.7/lib/rubygems/gem_runner.rb:56:in `run'
	setup.rb:36:in `<main>'
ERROR:  Loading command: install (LoadError)
	cannot load such file -- /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/vendored_optparse
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:9:in `require_relative'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:9:in `<top (required)>'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:3:in `require_relative'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/commands/install_command.rb:3:in `<top (required)>'
	<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:236:in `load_and_instantiate'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:137:in `[]'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:209:in `find_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:251:in `invoke_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/usr/local/bin/gem:10:in `<main>'
ERROR:  While executing gem ... (NoMethodError)
    undefined method `deprecated?' for nil:NilClass

    cmd.deprecation_warning if cmd.deprecated?
                                  ^^^^^^^^^^^^
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:252:in `invoke_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/usr/local/bin/gem:10:in `<main>'

      ```

**Comment by stepsysadmin** [comment]
> @stepsysadmin so your problem is solved? Don't forget to grab fresh docker-compose.yml before trying to test :)

Yes, fixed for me! Thanks!

**Comment by stepsysadmin** [comment]
Fixed in v. 0.1.4.1
