### ISSUE TITLE
0.22.0 dawarich_app fails to start : `cannot load such file -- /usr/local/bundle/gems/bundler-2.5.21/exe/bundle (LoadError)`

### ISSUE THREAD

**Issue by gboudreau** [Freika/dawarich#638]
In 0.21.6, I had this in my docker-compose:
```
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
```

Was working as expected:
```
dawarich_app    | Fetching rubygems-update-3.5.7.gem
dawarich_app    | Successfully installed rubygems-update-3.5.7
dawarich_app    | Installing RubyGems 3.5.7
dawarich_app    |   Successfully built RubyGem
dawarich_app    |   Name: bundler
dawarich_app    |   Version: 2.5.7
dawarich_app    |   File: bundler-2.5.7.gem
dawarich_app    | Bundler 2.5.7 installed
dawarich_app    | RubyGems 3.5.7 installed
dawarich_app    | Regenerating binstubs
dawarich_app    | Regenerating plugins
dawarich_app    | 
dawarich_app    | 
dawarich_app    | 
dawarich_app    | ------------------------------------------------------------------------------
dawarich_app    | 
dawarich_app    | RubyGems installed the following executables:
dawarich_app    | 	/usr/local/bin/gem
dawarich_app    | 	/usr/local/bin/bundle
dawarich_app    | 	/usr/local/bin/bundler
dawarich_app    | 
dawarich_app    | RubyGems system software updated
dawarich_app    | Fetching bundler-2.5.9.gem
dawarich_app    | Successfully installed bundler-2.5.9
dawarich_app    | 1 gem installed
dawarich_app    | 
dawarich_app    | A new release of RubyGems is available: 3.5.7 → 3.6.2!
dawarich_app    | Run `gem update --system 3.6.2` to update your installation.
dawarich_app    | 
dawarich_app    | Database dawarich_development already exists, skipping creation...
dawarich_app    | PostgreSQL is ready. Running database migrations...
...
dawarich_app    | 16:20:23 web.1  | [149] * Listening on http://[::]:3000
dawarich_app    | 16:20:23 web.1  | [149] Use Ctrl-C to stop
dawarich_app    | 16:20:23 web.1  | [149] - Worker 0 (PID: 163) booted in 0.01s, phase: 0
dawarich_app    | 16:20:23 web.1  | [149] - Worker 1 (PID: 170) booted in 0.01s, phase: 0
dawarich_app    | 16:20:23 web.1  | [149] - Worker 2 (PID: 179) booted in 0.07s, phase: 0
```

But on 0.22.0, I now have this in my docker-compose:
```
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
```

But that fails with the following error:
```
dawarich_app    | ✅ PostgreSQL is ready!
dawarich_app    | PostgreSQL is ready. Running database migrations...
dawarich_app    | /usr/local/bundle/bin/bundle:25:in `load': cannot load such file -- /usr/local/bundle/gems/bundler-2.5.21/exe/bundle (LoadError)
dawarich_app    | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
dawarich_app exited with code 0
```

full docker-compose.yml:
```yaml
networks:
  dawarich:

services:
  dawarich_redis:
    image: redis:7.0-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - ${SHARED_DATA_LOCATION}:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  dawarich_db:
    image: postgres:14.2-alpine
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - ${SHARED_DATA_LOCATION}:/var/shared
      - ${DB_CONF_LOCATION}:/etc/postgresql/postgresql.conf
    networks:
      - dawarich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - ${GEM_CACHE_LOCATION}app:/usr/local/bundle/gems
      - ${PUBLIC_LOCATION}:/var/app/public
      - ${WATCHED_LOCATION}:/var/app/tmp/imports/watched
    networks:
      - dawarich
    ports:
      - 2284:3000
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost,dawarich.patati.ca
      TIME_ZONE: America/Toronto
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      REVERSE_GEOCODING_ENABLED: true
      PHOTON_API_HOST: photon.home.patati.ca
      WEB_CONCURRENCY: 3
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - ${GEM_CACHE_LOCATION}sidekiq:/usr/local/bundle/gems
      - ${PUBLIC_LOCATION}:/var/app/public
      - ${WATCHED_LOCATION}:/var/app/tmp/imports/watched
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: localhost
      APPLICATION_HOSTS: localhost,dawarich.patati.ca
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      REVERSE_GEOCODING_ENABLED: true
      PHOTON_API_HOST: photon.home.patati.ca
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "bundle exec sidekiqmon processes | grep $${HOSTNAME}" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '4G'    # Limit memory usage to 4GB
```

**Comment by Freika** [comment]
You have probably meant 0.22.0 version.

Got same issue, solved by changing both sidekiq and app containers to use single volume for gem caching, in your case:

```
  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - ${GEM_CACHE_LOCATION}:/usr/local/bundle/gems
  dawarich_sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    volumes:
      - ${GEM_CACHE_LOCATION}:/usr/local/bundle/gems
```

Let me know if it helps

**Comment by gboudreau** [comment]
I had it that way before, but your new docker-compose uses different volumes for those two containers.

I tried to go back to using the same gem cache folder for both containers, but I still get the same error.
It looks like it's trying to use bundler-2.5.21 before installing it...

Here's my complete log:
```
dawarich_redis  | 1:C 09 Jan 2025 16:52:09.934 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
dawarich_redis  | 1:C 09 Jan 2025 16:52:09.934 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
dawarich_redis  | 1:C 09 Jan 2025 16:52:09.934 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
dawarich_redis  | 1:M 09 Jan 2025 16:52:09.935 * monotonic clock: POSIX clock_gettime
dawarich_redis  | 1:M 09 Jan 2025 16:52:09.937 * Running mode=standalone, port=6379.
dawarich_redis  | 1:M 09 Jan 2025 16:52:09.937 # Server initialized
dawarich_redis  | 1:M 09 Jan 2025 16:52:09.937 * Loading RDB produced by version 7.0.15
dawarich_redis  | 1:M 09 Jan 2025 16:52:09.937 * RDB age 3 seconds
dawarich_redis  | 1:M 09 Jan 2025 16:52:09.937 * RDB memory usage when created 1.80 Mb
dawarich_redis  | 1:M 09 Jan 2025 16:52:09.939 * Done loading RDB, keys loaded: 410, keys expired: 0.
dawarich_redis  | 1:M 09 Jan 2025 16:52:09.939 * DB loaded from disk: 0.002 seconds
dawarich_redis  | 1:M 09 Jan 2025 16:52:09.939 * Ready to accept connections
dawarich_db     | 
dawarich_db     | PostgreSQL Database directory appears to contain a database; Skipping initialization
dawarich_db     | 
dawarich_db     | 2025-01-09 16:52:10.093 UTC [1] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
dawarich_db     | 2025-01-09 16:52:10.094 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dawarich_db     | 2025-01-09 16:52:10.094 UTC [1] LOG:  listening on IPv6 address "::", port 5432
dawarich_db     | 2025-01-09 16:52:10.108 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dawarich_db     | 2025-01-09 16:52:10.137 UTC [21] LOG:  database system was shut down at 2025-01-09 16:52:06 UTC
dawarich_db     | 2025-01-09 16:52:10.217 UTC [1] LOG:  database system is ready to accept connections
dawarich_app    | ✅ PostgreSQL is ready!
dawarich_app    | PostgreSQL is ready. Running database migrations...
dawarich_app    | /usr/local/bundle/bin/bundle:25:in `load': cannot load such file -- /usr/local/bundle/gems/bundler-2.5.21/exe/bundle (LoadError)
dawarich_app    | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
dawarich_app exited with code 0
```

See how it does not try to install bundler...
My gem cache folder stays empty.

**Comment by gboudreau** [comment]
My guess is that it works for you because you already have a `bundler-2.5.21` folder in your gem cache volume.
If you try with an empty volume for the gem cache, you should get the same error I get.

**Comment by theAlevan** [comment]
I get the same error. After I updated the docker-compose file and recreated the containers with the new image, I get this error:

`/usr/local/bundle/bin/bundle:25:in `load': cannot load such file -- /usr/local/bundle/gems/bundler-2.5.21/exe/bundle (LoadError) from /usr/local/bundle/bin/bundle:25:in `<main>'`

In the gem cache directory, this is the only bundler dir: **bundler-2.5.9**

**Comment by Freika** [comment]
Okay, got an idea.

@gboudreau @theAlevan can you remove completely gem caching volumes from your compose file and try starting the app?

**Comment by alternativesurfer** [comment]
Same, with the gem cache commented out, everything starts without issue.

What is the downside of removing the gem cache?

**Comment by gboudreau** [comment]
So I guess the gems are part of the image, in `/usr/local/bundle/gems`..?

What was the goal in creating a volume for those? Since they are already in the image, I fail to see how using a volume helps (us, run the image - maybe it helps you when you develop..?)

**Comment by Freika** [comment]
I guess I oversaw it at some point and didn't pay too much attention to docker-related files. The main idea is to have gems cached when they are being installed outside of the image building process, but having them built in to the docker image makes caching volume existence little to no sense, so feel free to just remove these lines from your compose files.

I'll do the same in the next release, with appropriate mention in the release notes.

Thanks for helping me to sort this out!

**Comment by Freika** [comment]
Fixed in 0.22.1

**Comment by andreapx** [comment]
> Fixed in 0.22.1

Hi @Freika I'm using the "freikin/dawarich:latest", so it should be 0.23.5, right? But I'm still having this problem

**Comment by Freika** [comment]
@andreapx remove your gem caching volumes from docker compose

**Comment by andreapx** [comment]
> [@andreapx](https://github.com/andreapx) remove your gem caching volumes from docker compose

Ops, I missed that.
I've now removed it and Dawarich is up and running.
Thanks!!!
